# baseURL
@baseURL = http://localhost:3000

###
# Admin - Find All Users
GET {{ baseURL }}/v1/users

###
# Admin - Find User By Id
GET {{ baseURL }}/v1/users/1

###
# Admin - Create User
POST {{ baseURL }}/v1/users
Content-Type: application/json

{
    "email": "example@email.com",
    "password": "password"
}

###
# Admin - Modify User By Id
PUT {{ baseURL }}/v1/users/1
Content-Type: application/json

{
    "email": "example@email.com",
    "password": "password"
}

###
# Admin - Delete User By Id
DELETE {{ baseURL }}/v1/users/1
